name: Main Workflow

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Setup .NET Core 3.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.x
    
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test
